[package]
name = "home-automation-tapo"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
actix = "0.13"
actix-web = "4.4"
anyhow = "1.0"
config = "0.13"
derive_more = "0.99"
log = "0.4"
paho-mqtt = "0.12"
pretty_env_logger = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tapo = "0.7"

[dev-dependencies]
actix-rt = "2.9"
tokio = { version = "1.36", features = ["rt", "macros"] }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
