[package]
name = "home-automation-tapo"
version = "0.1.2"
edition = "2021"
license = "MIT"

[dependencies]
actix = "0.13"
actix-web = "4.9"
anyhow = "1.0"
config = "0.14"
derive_more = { version = "1.0", features = ["display"] }
log = "0.4"
paho-mqtt = "0.12"
pretty_env_logger = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tapo = "0.7"

[dev-dependencies]
actix-rt = "2.10"
tokio = { version = "1.42", features = ["rt", "macros"] }
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
