resources:
  - deployment.yaml
  - vault-secret.yaml

namespace: default

commonLabels:
  app.kubernetes.io/part-of: home-automation
  app.kubernetes.io/name: tapo

images:
  - name: ghcr.io/mihai-dinculescu-lab/home-automation-tapo
    newTag: "main"
