apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: home-automation-tapo-secrets-sync
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: home-automation/tapo
  destination:
    name: home-automation-tapo-secrets
    create: true
    overwrite: true
  refreshAfter: 1h
